Implementation of TimeStamps for events #56
delphi-hub/delphi-registry pull request #61
Opened 2018-12-06 16:02 UTC by Ayybeeshafi

Last branch had come conflicts with the develop branch. This one is up to date.

2018-12-07 12:34 UTC, johannesduesing requested changes
Thanks for your PR :+1: . Please address the codestyle issues mentioned in my comments below.

2018-12-07 12:34 UTC, johannesduesing commented on src/main/scala/de/upb/cs/swt/delphi/instanceregistry/io/swagger/client/model/Event.scala
> +  implicit val timestamp: JsonFormat[DateTime] = new JsonFormat[DateTime] {
Please rename this val to ```timestampFormat``` to be consistent with the other formats. Also please add JavaDoc comments to this val.

2018-12-07 12:34 UTC, johannesduesing commented on src/main/scala/de/upb/cs/swt/delphi/instanceregistry/io/swagger/client/model/Event.scala
> +          case _ => throw new DeserializationException("Failed to parse date time [" + value + "].")
Please remove the ```new``` keyword here, it is not necessary and marked as warning by IntelliJ.

2018-12-07 12:34 UTC, johannesduesing commented on src/main/scala/de/upb/cs/swt/delphi/instanceregistry/io/swagger/client/model/Event.scala
> +      case _ => throw new DeserializationException("Failed to parse json string [" + json + "].")
Please remove the ```new``` keyword here, it is not necessary and marked as warning by IntelliJ.

2018-12-07 12:34 UTC, johannesduesing commented on src/main/scala/de/upb/cs/swt/delphi/instanceregistry/io/swagger/client/model/Event.scala
> +    RegistryEvent(EventType.NumbersChangedEvent, NumbersChangedPayload(componentType, newNumber),DateTime.now)
Please add a space after the comma. This also holds for the other occurrences below.

2018-12-07 13:28 UTC, Ayybeeshafi commented
@johannesduesing Thankyou for the review. Please verify the requested changes in the latest commit d4ce17e

2018-12-09 15:31 UTC, johannesduesing approved these changes
Thanks for the quick corrections :+1:

2018-12-09 15:36 UTC, merged