Fix for issue #59
delphi-hub/delphi-registry pull request #71
Opened 2018-12-28 17:21 UTC by 24santoshr

**Reason for this PR**
Removing the alpine plugin to resolve #59 issue.

2018-12-28 17:39 UTC, bhermann requested changes
May I suggest the following solution used in all the other delphi projects:
```
  settings(
    dockerBaseImage := "openjdk:jre-alpine"
  ).
  enablePlugins(AshScriptPlugin).
```
The `AshScriptPlugin` alleviates the need to have `/bin/bash` installed.

2018-12-28 17:56 UTC, 24santoshr commented
Thanks @bhermann. The docker image runs now even with the plugin.

2018-12-28 18:00 UTC, bhermann approved these changes

2018-12-29 03:49 UTC, merged

2019-01-03 10:42 UTC, johannesduesing commented
@24santoshr thanks for the fix :+1: Next time, please merge this kind of changes into develop before merging them into master, the master branch should not be ahead of the develop branch.